repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.86.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      args: 
        - --args=--disable-rule=terraform_module_pinned_source
        - --args=--recursive
    # - id: terraform_validate # Uncommented since validation is extremely slow.
