variable "project_name" {
  description = "The name of the project/platform."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9]*$", var.project_name)) && length(var.project_name) == 8
    error_message = "The project name value must not contain special characters, and is max 4 characters long."
  }
}

variable "environment" {
  description = "The environment name. Eg, udev/uprd/ops etc."
  type        = string

  validation {
    condition     = length(var.environment) == 3
    error_message = "The environment must be 3 characters."
  }
}

variable "location" {
  type        = string
  description = "Azure Region to be used."
  default     = "westeurope"
}

variable "tags" {
  type        = map(string)
  description = "Collection of tags that help organizing resources (https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/decision-guides/resource-tagging/?toc=/azure/azure-resource-manager/management/toc.json)."
}

variable "log_analytics_workspace_id" {
  type    = string
  default = null
}

variable "prefix" {
  type        = string
  description = "Name prefix for all the created resources."
}

# variable "ops_technical_owners" {
#   type        = string
#   description = "Technical Owners of the platform"
# }

variable "runner_registration_token" {
  type        = string
  description = "Token used for registering a github action runner. Needs to be generated by an account admin."
  default     = ""
}