name: Manual destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

jobs:
  apply:
    runs-on: [self-hosted, linux]
    name: Destroy terraform
    environment: ${{ inputs.environment }}       
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TERRAFORM_PRE_RUN: |
        # Install latest Azure CLI
        curl -skL https://aka.ms/InstallAzureCLIDeb | bash
        az login --service-principal --tenant ${ARM_TENANT_ID} --username ${ARM_CLIENT_ID} --password ${ARM_CLIENT_SECRET} --output table
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform apply
        uses: dflook/terraform-destroy@v1
        with:
          auto_approve: true
          variables: |
            environment = "${{ inputs.environment }}"          
          var_file: env/${{ inputs.environment }}/vars/vars.tfvars
          backend_config_file: env/${{ inputs.environment }}/vars/backend-config.tfvars
